# Offense count: 4
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowMultipleStyles, EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle.
# SupportedHashRocketStyles: key, separator, table
# SupportedColonStyles: key, separator, table
# SupportedLastArgumentHashStyles: always_inspect, always_ignore, ignore_implicit, ignore_explicit
# Layout/HashAlignment:
#   Exclude:
#     - 'spec/spec_helper_acceptance_local.rb'

# Offense count: 43
# This cop supports unsafe autocorrection (--autocorrect-all).
Lint/BooleanSymbol:
  Exclude:
    - 'lib/puppet/provider/acl/windows.rb'
    - 'lib/puppet/provider/acl/windows/base.rb'
    - 'lib/puppet/type/acl.rb'
    - 'spec/integration/provider/acl/windows_spec.rb'
    - 'spec/unit/provider/acl/windows_spec.rb'
    - 'spec/unit/type/acl_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Lint/DuplicateRegexpCharacterClassElement:
#   Exclude:
#     - 'spec/acceptance/identity/specify_app_package_authority_idents_spec.rb'

# Offense count: 2
Lint/NoReturnInBeginEndBlocks:
  Exclude:
    - 'lib/puppet/provider/acl/windows/base.rb'

# Offense count: 6
# This cop supports unsafe autocorrection (--autocorrect-all).
Lint/NonAtomicFileOperation:
  Exclude:
    - 'spec/integration/provider/acl/windows_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Lint/RedundantCopDisableDirective:
  Exclude:
    - 'lib/puppet/provider/acl/windows/base.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Lint/RedundantCopEnableDirective:
  Exclude:
    - 'spec/unit/type/acl_spec.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: AllowedMethods.
# AllowedMethods: instance_of?, kind_of?, is_a?, eql?, respond_to?, equal?
Lint/RedundantSafeNavigation:
  Exclude:
    - 'lib/puppet/type/acl/ace.rb'

# Offense count: 16
# Configuration parameters: AllowedMethods, AllowedPatterns, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 50

# Offense count: 7
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns, inherit_mode.
# AllowedMethods: refine
Metrics/BlockLength:
  Max: 381

# Offense count: 1
# Configuration parameters: CountComments, CountAsOne.
Metrics/ClassLength:
  Max: 252

# Offense count: 12
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/CyclomaticComplexity:
  Max: 15

# Offense count: 20
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
Metrics/MethodLength:
  Max: 46

# Offense count: 1
# Configuration parameters: CountComments, CountAsOne.
Metrics/ModuleLength:
  Max: 364

# Offense count: 10
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/PerceivedComplexity:
  Max: 16

# Offense count: 5
Naming/AccessorMethodName:
  Exclude:
    - 'lib/puppet/provider/acl/windows/base.rb'
    - 'spec/integration/provider/acl/windows_spec.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: PreferredName.
Naming/RescuedExceptionsVariableName:
  Exclude:
    - 'lib/puppet/provider/acl/windows/base.rb'

# Offense count: 5
# This cop supports unsafe autocorrection (--autocorrect-all).
Performance/StringInclude:
  Exclude:
    - 'spec/unit/provider/acl/windows_spec.rb'
    - 'spec/unit/type/acl_spec.rb'

# Offense count: 2
# This cop supports unsafe autocorrection (--autocorrect-all).
RSpec/BeEq:
  Exclude:
    - 'spec/integration/provider/acl/windows_spec.rb'

# Offense count: 20
# This cop supports safe autocorrection (--autocorrect).
RSpec/ContextMethod:
  Exclude:
    - 'spec/integration/provider/acl/windows_spec.rb'
    - 'spec/unit/provider/acl/windows_spec.rb'
    - 'spec/unit/type/acl/ace_spec.rb'

# Offense count: 186
# Configuration parameters: Prefixes, AllowedPatterns.
# Prefixes: when, with, without
RSpec/ContextWording:
  Enabled: false

# Offense count: 41
# Configuration parameters: IgnoredMetadata.
RSpec/DescribeClass:
  Enabled: false

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowConsecutiveOneLiners.
RSpec/EmptyLineAfterExample:
  Exclude:
    - 'spec/unit/type/acl_spec.rb'

# Offense count: 51
# Configuration parameters: CountAsOne.
RSpec/ExampleLength:
  Max: 40

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
RSpec/ExcessiveDocstringSpacing:
  Exclude:
    - 'spec/acceptance/use_cases/multiple_aces_spec.rb'

# Offense count: 60
# Configuration parameters: Max.
RSpec/IndexedLet:
  Exclude:
    - 'spec/acceptance/propagation/prop_file_spec.rb'
    - 'spec/acceptance/purge/purge_all_other_perms_dir_spec.rb'
    - 'spec/acceptance/purge/purge_all_other_perms_file_spec.rb'
    - 'spec/acceptance/purge/purge_explicit_perms_dir_spec.rb'
    - 'spec/acceptance/purge/purge_explicit_perms_file_spec.rb'
    - 'spec/acceptance/use_cases/complex_prop_inherit_spec.rb'
    - 'spec/acceptance/use_cases/multiple_aces_spec.rb'
    - 'spec/acceptance/use_cases/multiple_acls_shared_ident_spec.rb'
    - 'spec/acceptance/use_cases/multiple_acls_spec.rb'

# Offense count: 100
RSpec/MultipleExpectations:
  Max: 12

# Offense count: 102
# Configuration parameters: AllowSubject.
RSpec/MultipleMemoizedHelpers:
  Max: 27

# Offense count: 8
# Configuration parameters: AllowedGroups.
RSpec/NestedGroups:
  Max: 4

# Offense count: 104
# Configuration parameters: AllowedPatterns.
# AllowedPatterns: ^expect_, ^assert_
RSpec/NoExpectationExample:
  Enabled: false

# Offense count: 4
# This cop supports safe autocorrection (--autocorrect).
RSpec/ReceiveNever:
  Exclude:
    - 'spec/integration/provider/acl/windows_spec.rb'
    - 'spec/unit/type/acl_spec.rb'

# Offense count: 14
RSpec/StubbedMock:
  Exclude:
    - 'spec/unit/provider/acl/windows_spec.rb'
    - 'spec/unit/type/acl/ace_spec.rb'
    - 'spec/unit/type/acl_spec.rb'

# Offense count: 1
Security/CompoundHash:
  Exclude:
    - 'lib/puppet/type/acl/ace.rb'

# Offense count: 8
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: separated, grouped
Style/AccessorGrouping:
  Exclude:
    - 'lib/puppet/type/acl/ace.rb'
    - 'lib/puppet/type/acl/rights.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: MinBranchesCount.
Style/CaseLikeIf:
  Exclude:
    - 'lib/puppet/type/acl.rb'

# Offense count: 3
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'lib/puppet/provider/acl/windows/base.rb'
    - 'lib/puppet/type/acl/ace.rb'
    - 'lib/puppet/type/acl/rights.rb'

# Offense count: 1
# Configuration parameters: MinBranchesCount.
Style/HashLikeCase:
  Exclude:
    - 'lib/puppet/type/acl/rights.rb'

# Offense count: 30
# This cop supports safe autocorrection (--autocorrect).
Style/IfUnlessModifier:
  Exclude:
    - 'lib/puppet/provider/acl/windows.rb'
    - 'lib/puppet/provider/acl/windows/base.rb'
    - 'lib/puppet/type/acl.rb'
    - 'lib/puppet/type/acl/ace.rb'
    - 'spec/spec_helper_local.rb'

# Offense count: 2
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: AllowedMethods.
# AllowedMethods: nonzero?
Style/IfWithBooleanLiteralBranches:
  Exclude:
    - 'lib/puppet/type/acl.rb'

# Offense count: 1
Style/MixinUsage:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 3
# Configuration parameters: AllowedMethods.
# AllowedMethods: respond_to_missing?
Style/OptionalBooleanParameter:
  Exclude:
    - 'lib/puppet/provider/acl/windows/base.rb'
    - 'spec/integration/provider/acl/windows_spec.rb'

# Offense count: 4
# This cop supports safe autocorrection (--autocorrect).
Style/RedundantAssignment:
  Exclude:
    - 'lib/puppet/provider/acl/windows/base.rb'
    - 'spec/spec_helper_acceptance_local.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Style/RedundantCondition:
  Exclude:
    - 'lib/puppet/provider/acl/windows/base.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
Style/RedundantConstantBase:
  Exclude:
    - 'lib/puppet/provider/acl/windows.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
Style/RedundantRegexpEscape:
  Exclude:
    - 'spec/acceptance/purge/purge_all_other_perms_dir_spec.rb'

# Offense count: 3
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: implicit, explicit
Style/RescueStandardError:
  Exclude:
    - 'lib/puppet/provider/acl/windows/base.rb'
    - 'spec/spec_helper.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowModifier.
Style/SoleNestedConditional:
  Exclude:
    - 'lib/puppet/type/acl/ace.rb'

# Offense count: 8
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: Mode.
Style/StringConcatenation:
  Exclude:
    - 'lib/puppet/provider/acl/windows.rb'
    - 'lib/puppet/provider/acl/windows/base.rb'
    - 'lib/puppet/type/acl.rb'
    - 'lib/puppet/type/acl/ace.rb'
    - 'spec/acceptance/parameter_target/perms_on_dir_spec.rb'
    - 'spec/acceptance/parameter_target/perms_on_file_spec.rb'
    - 'spec/spec_helper_acceptance_local.rb'

# Offense count: 4
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: AllowMethodsWithArguments, AllowedMethods, AllowedPatterns, AllowComments.
# AllowedMethods: define_method
Style/SymbolProc:
  Exclude:
    - 'lib/puppet/provider/acl/windows.rb'
    - 'lib/puppet/provider/acl/windows/base.rb'
    - 'spec/integration/provider/acl/windows_spec.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInHashLiteral:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'spec/spec_helper_acceptance_local.rb'
